const AUDIT_ACTION_LABELS: Record<string, string> = {
  "appointment.created": "إنشاء موعد",
  "appointment.customer_booked": "حجز العميل موعدًا",
  "appointment.customer_cancelled": "إلغاء العميل موعدًا",
  "appointment.status_changed": "تغيير حالة موعد",
  "attendance.check_in": "تسجيل حضور",
  "attendance.check_out": "تسجيل انصراف",
  "auth.dashboard_login_success": "دخول ناجح للوحة الإدارة",
  "auth.dashboard_login_failed": "محاولة دخول فاشلة",
  "auth.barber_login_success": "دخول ناجح للحلاق",
  "auth.barber_login_failed": "محاولة دخول حلاق فاشلة",
  "auth.logout": "تسجيل خروج",
  "barber.created": "إضافة حلاق",
  "barber.deleted": "حذف حلاق",
  "barber.pin_reset": "إعادة تعيين رمز حلاق",
  "billing.invoice_voided": "إلغاء فاتورة اشتراك",
  "billing.payment_approved": "اعتماد دفعة اشتراك",
  "billing.payment_recorded": "تسجيل دفعة اشتراك",
  "billing.payment_rejected": "رفض طلب دفع",
  "billing.payment_requested": "إرسال طلب دفع",
  "campaign.created": "إنشاء حملة",
  "campaign.redeemed": "استخدام حملة",
  "cash_expense.deleted": "حذف مصروف",
  "cash_expense.recorded": "تسجيل مصروف",
  "cash_session.closed": "إغلاق جلسة صندوق",
  "cash_session.opened": "فتح جلسة صندوق",
  "customer.portal_token_rotated": "تجديد رابط بوابة عميل",
  "customer.self_registered": "تسجيل عميل جديد",
  "daily_close.created": "إنشاء إغلاق يومي",
  "manager_reward.created": "منح مكافأة مدير",
  "manager_reward.redeemed": "استخدام مكافأة مدير",
  "organization.created": "إنشاء مؤسسة",
  "platform.barber_pin_reset": "إعادة تعيين رمز حلاق من المنصة",
  "platform.member_password_reset": "إعادة تعيين كلمة مرور عضو",
  "platform.organization_deleted": "حذف مؤسسة",
  "platform.organization_updated": "تحديث مؤسسة",
  "product.created": "إضافة منتج",
  "product.updated": "تحديث منتج",
  "reward_rule.created": "إنشاء قاعدة مكافأة",
  "salon.created": "إضافة فرع",
  "salon.deleted": "حذف فرع",
  "salon.updated": "تحديث فرع",
  "service.created": "إضافة خدمة",
  "staff.created": "إضافة عضو إدارة",
  "staff.deleted": "حذف عضو إدارة",
  "system_settings.updated": "تحديث إعدادات التشغيل",
  "visit.amount_updated": "تعديل مبلغ زيارة",
  "visit.cancelled": "إلغاء زيارة",
  "visit.confirmed": "تأكيد زيارة",
  "visit.payment_method_updated": "تعديل طريقة الدفع",
  "visit.post_close_adjustment": "تصحيح زيارة بعد الإغلاق",
  "whatsapp.customer_preference_updated": "تحديث موافقة واتساب",
  "whatsapp.message_drafted": "تجهيز رسالة واتساب",
  "whatsapp.message_marked_sent": "تأكيد إرسال رسالة",
  "whatsapp.message_opened": "فتح رسالة واتساب",
  "whatsapp.safety_settings_updated": "تحديث ضوابط واتساب",
  "whatsapp.template_created": "إنشاء قالب واتساب",
};

const AUDIT_ENTITY_LABELS: Record<string, string> = {
  Appointment: "موعد",
  AttendanceRecord: "حضور",
  Barber: "حلاق",
  BillingInvoice: "فاتورة اشتراك",
  Campaign: "حملة",
  CashExpense: "مصروف",
  CashSession: "جلسة صندوق",
  Customer: "عميل",
  DailyClose: "إغلاق يومي",
  Organization: "مؤسسة",
  Product: "منتج",
  RewardRule: "قاعدة مكافأة",
  Salon: "فرع",
  Service: "خدمة",
  SystemSettings: "إعدادات",
  User: "عضو إدارة",
  Visit: "زيارة",
  WhatsAppMessage: "رسالة واتساب",
  WhatsAppTemplate: "قالب واتساب",
};

export function auditActionLabel(action: string) {
  return AUDIT_ACTION_LABELS[action] ?? "إجراء إداري";
}

export function auditEntityLabel(entityType: string) {
  return AUDIT_ENTITY_LABELS[entityType] ?? "سجل";
}
